// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI1len8G7CcvdQIMoK7HwDCeg6cDOXtpE',
    appId: '1:1025877417545:web:2f88ba675896d40b392998',
    messagingSenderId: '1025877417545',
    projectId: 'survey-test-52843',
    authDomain: 'survey-test-52843.firebaseapp.com',
    storageBucket: 'survey-test-52843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQEP8mCzmkVIdvG2ZstvXq8ONWEtRRCw',
    appId: '1:1025877417545:android:e7f15b54b7c275f5392998',
    messagingSenderId: '1025877417545',
    projectId: 'survey-test-52843',
    storageBucket: 'survey-test-52843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JbKEZPAcsCv2AkwhC4TpdsQ4g7W_y6Y',
    appId: '1:1025877417545:ios:b6fddf0f92c636bc392998',
    messagingSenderId: '1025877417545',
    projectId: 'survey-test-52843',
    storageBucket: 'survey-test-52843.appspot.com',
    iosClientId: '1025877417545-7tdhf74p4fkgk2k4587nnp6vhk849spo.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyapp',
  );
}
